function verse_of_day() { 
	
	var citat = new Array(
				"<p>Ja Herrasi on määrännyt, että palvelette yksin Häntä, ja teidän tulee tehdä hyvää vanhemmillenne. Jos toinen heistä tahi molemmat saavuttavat korkean iän sinun luonasi, älä halveksi äläkä soimaa heitä, vaan puhuttele heitä kunnioittavasti. Ja myötätunnolla ojenna kätesi heitä kohti ja lausu sävyisästi: »Oi Herra, ole laupias heille, sillä he kasvattivat minua, kun olin pieni.» </p><hr><p class='mb-0'>Koraani (17:23-24)</p>",
				"<p>Hänelle, Armahtajalle, joka on noussut valtaistuimelleen, kuuluu kaikki, mitä on taivaassa ja mitä on maan päällä, mitä on niiden välillä ja maan alla. Siksi ei sinun tarvitse rukoilla kovalla äänellä; sillä Hän tietää yhtä hyvin salaisen ja kätketyn. Ei ole muita jumalia kuin Jumala; hänelle kuuluvat ihanimmat nimitykset. </p><hr><p class='mb-0'>Koraani (20:5-8)</p>",
				"<p>Oi ihmiset! Kunnioittakaa peläten Herraanne. Totisesti, (tuomion) hetken järkytys on hirmuinen tapahtuma.Sinä päivänä, jolloin sen tulette näkemään, jokainen imettävä vaimo hämääntyy unohtaen imettämänsä lapsen ja jokainen raskaana oleva nainen synnyttää sikiönsä kesken. Olet näkevä ihmiset ikäänkuin päihtyneinä, mutta he eivät ole humalassa, vaan Jumalan rangaistus tulee ankarana. </p><hr><p class='mb-0'>Koraani (22:1-2)</p>",
				"<p>Totisesti muovailimme ihmisen puhtaasta savesta. Sitten sijoitimme elon siemenen varmaan suojaan. Senjälkeen kehitimme siemenestä verenalun, ja hyytyneestä verestä kehitimme lihanrungon; lihanrungossa rakensimme luut ja luut ympäröimme lihalla. Tämän jälkeen saatoimme hänet uuteen hahmoon. Siunattu olkoon siis Jumala, luojista paras. Tämän jälkeen teidän on totisesti kuoltava; mutta ylösnousemuksen päivänä teidät jälleen herätetään eloon. </p><hr><p class='mb-0'>Koraani (23:12-14)</p>",
				"<p>Luulitteko, että olimme luonut teidät turhan vuoksi ja ettei teidän ollut palattava Meidän luoksemme?» Korkea on Jumala, totuuden kuningas; ei ole muuta jumalaa kuin Hän, ylevän voiman Herra. Ken rukoilee jotakin muuta jumalaa Herran ohella, hänen osaksensa ei tule valoa, ja hänen on tili tehtävä Jumalalle. Totisesti, uskottomilla ei ole milloinkaan menestystä. </p><hr><p class='mb-0'>(Koraani 23:115-117)</p>",
				"<p>Sanokaa: &raquo;Me uskomme Jumalaan ja siihen, mik&auml; on ilmoitettu meille ja mik&auml; on ilmoitettu Aabrahamille, Ismaelille, Iisakille ja Jaakobille ja Israelin sukukunnille.  </p><hr><p class='mb-0'>Koraani (2:136)</p>",
				"<p>Ja Herrasi on määrännyt, että palvelette yksin Häntä, ja teidän tulee tehdä hyvää vanhemmillenne. Jos toinen heistä tahi molemmat saavuttavat korkean iän sinun luonasi, älä halveksi äläkä soimaa heitä, vaan puhuttele heitä kunnioittavasti. Ja myötätunnolla ojenna kätesi heitä kohti ja lausu sävyisästi: »Oi Herra, ole laupias heille, sillä he kasvattivat minua, kun olin pieni.» </p><hr><p class='mb-0'>Koraani (17:23-24)</p>",
				"<p>Uskonnossa ei ole mit&auml;&auml;n pakkoa, oikea tie on selv&auml;sti erotettu harhateist&auml;, ja se, joka hylk&auml;&auml; saatanan ja uskoo Jumalaan, h&auml;n pit&auml;&auml; kiinni mit&auml; lujimmasta k&auml;densijasta, joka ei murru.  Jumalahan on kuuleva, tiet&auml;v&auml;. </p><hr><p class='mb-0'>Koraani (2:256)</p>",
				"<p>Kehoita siis edelleenkin heitä oikeaan uskoon ja käy vakaana oikeaa tietä, niinkuin sinua on käsketty, äläkä noudata heidän alhaisia toiveitaan, vaan sano: »Minä uskon siihen, mitä Jumala on Kirjoituksessa ilmoittanut, ja minut on määrätty jakamaan teille oikeutta. Jumala on meidän ja teidän Herranne. Meillä on oleva tekomme ja teillä tekonne. Riita ei ole tarpeen välillämme; Jumala kokoaa meidät, ja Hänen tykönänsä on matkamme pää. </p><hr><p class='mb-0'>Koraani (42:15)</p>",
				"<p>Hyvä ja paha eivät ole samanlaisia. Karkoita paha sillä, mikä on parempaa, ja katso se, jonka kanssa olit vihoissa, on kuin hyvä ystäväsi. </p><hr><p class='mb-0'>Koraani (41:34)</p>",
				"<p>Älä ole ylpeä ihmisiä kohtaan, äläkä vaella maassa pöyhkeänä. Totisesti, Jumala ei rakasta omahyväistä kerskuria. Hillitse itsesi ja puhu sävyisästi. Totisesti, rumin ääni on aasin hirnunta. </p><hr><p class='mb-0'>Koraani (31:18-19)</p>",
				"<p>Ihmiset, Me olemme totisesti luonut teidät miehestä ja naisesta ja jakanut teidät heimoihin ja sukuihin, jotta tuntisitte toinen toisenne. Arvokkain teistä Jumalan tykönä on se, joka parhaiten pitää huolen velvollisuudestaan. Jumala on totisesti tietävä, tajuava. </p><hr><p class='mb-0'>Koraani (49:13)</p>",
				"<p>Olemme myös määrännyt ihmisen pitämään huolta vanhemmistaan; hänen äitinsä on kantanut häntä äärimmäiseen uupumukseen saakka, ja hänen vieroittamisensa on kestänyt toista vuotta. Kiitä Minua ja molempia vanhempiasi. Minun luokseni on kaikkien palattava. </p><hr><p class='mb-0'>Koraani (31:14)</p>",
				"<p>Mutta jos he olisivat uskoneet ja karttaneet pahaa, niin olisi palkkio Jumalalta ollut parempi. Jospa he vain tiet&auml;isiv&auml;t sen! </p><hr><p class='mb-0'>Koraani (2:103)</p>",
				"<p>Jumala ei ket&auml;&auml;n rasita yli voimien; mit&auml; kukin on aikaansaanut, on h&auml;nen edukseen, ja h&auml;nt&auml; vastaan nousee vain se, mink&auml; h&auml;n itse on aiheuttanut.  Herramme, &auml;l&auml; rankaise meit&auml;, jos hairahdumme tai rikomme!  Herra, &auml;l&auml; pane kannettavaksemme sellaista taakkaa, kuin annoit niiden osaksi, jotka ovat ennen meit&auml; el&auml;neet!  Herra, &auml;l&auml; pakota meit&auml; kantamaan sit&auml;, mihin eiv&auml;t voimamme riit&auml;!  Ole pitk&auml;mielinen, anna anteeksi ja armahda meit&auml;!  Olet suojelijamme; auta meit&auml; uskottomia vastaan! </p><hr><p class='mb-0'>Koraani (2:286)</p>",
				"<p>Sanokaa: &raquo;Me uskomme Jumalaan ja siihen, mik&auml; on ilmoitettu meille ja mik&auml; on ilmoitettu Aabrahamille, Ismaelille, Iisakille ja Jaakobille ja Israelin sukukunnille. </p><hr><p class='mb-0'>Koraani (2:136)</p>",
				"<p>N&auml;in Me olemme ilmaissut sinulle (Muhammed) Totuuden kirjan varmentaaksemme edelt&auml;k&auml;yneet kirjoitukset ja s&auml;ilytt&auml;&auml;ksemme niiden tarkkuuden; arvostele siis niit&auml; Jumalan ilmoituksen mukaisesti, &auml;l&auml;k&auml; seuraa sellaisten alhaisia vaistoja, jotka luopuvat sinulle ilmaistusta totuudesta; kullekin (heimollenne) Me s&auml;&auml;simme omat lakinsa ja tapansa. Jos olisi ollut Jumalan tahto, H&auml;n olisi muovaillut teid&auml;t kaikki yhdeksi kansaksi, ellei H&auml;n olisi tahtonut koetella teit&auml; erikseen annetuin totuuksin; sent&auml;hden rient&auml;k&auml;&auml; kilvan toistenne kanssa hyveiden harjoittamiseen.  Kaikkien on teid&auml;n palattava Jumalan eteen, ja H&auml;n kyll&auml; antaa teille lopullisen selvyyden siit&auml;, mist&auml; olitte erimielisi&auml;. </p><hr><p class='mb-0'>Koraani (5:48)</p>",
				"<p>Mielett&ouml;m&auml;t ihmiset tulevat sanomaan: &raquo;Mik&auml; on k&auml;&auml;nt&auml;nyt heid&auml;t pois heid&auml;n  kiblastaan, jota p&auml;in he ennen suuntautuivat rukoillessaan?&raquo; Sano: &raquo;Jumalalle kuuluu It&auml; ja L&auml;nsi.  H&auml;n johtaa kenet tahtoo oikealle tielle.&raquo;. Siten Me olemme tehnyt teid&auml;t (arabialaiset) v&auml;litt&auml;j&auml;kansaksi, ett&auml; te olisitte todistajia ihmisten edess&auml; ja profeetta Muhammed olisi todistajana teid&auml;n edess&auml;nne.  Kiblan, johon te ennen suuntauduitte, m&auml;&auml;r&auml;simme ainoastaan erottaaksemme sen, joka seuraa profeettaa, siit&auml;, joka per&auml;ytyy h&auml;nen luotaan takaisin. ja se oli totisesti vaikea koetus, paitsi niille, joita Jumala johtaa; mutta Jumalan tarkoitus ei ollut tehd&auml; uskoanne turhaksi, sill&auml; Jumala on totisesti lempe&auml; ja laupias ihmisi&auml; kohtaan.</p><hr><p class='mb-0'>Koraani (2:142-143)</p>",
				"<p>Vai sanovatko he: »Hän on sepittänyt valheita Jumalasta?» Mutta jos Jumala tahtoo, Hän voi tehdä sydämesi kärsivälliseksi. Jumala pyyhkii pois valheen ja lujittaa totuuden sanoillaan; totisesti Hän tietää kaikki ajatuksenne. </p><hr><p class='mb-0'>Koraani (42:24)</p>",
				"<p>He tekevät myös enkeleistä, niistä, jotka ovat laupiaan Jumalan palvelijoita, naisolentoja.  Olivatko he edes silminnäkijöinä, kun loimme nämä enkelit?  Heidän todistuksensa kirjoitetaan muistiin, ja heitä tullaan kuulustamaan.</p><hr><p class='mb-0'>Koraani (43:19)</p>",
				"<p>Ja Loot oli Meid&auml;n l&auml;hettil&auml;&auml;mme, kun h&auml;n puhui kansalleen:   &raquo;Harjoitatteko irstaisuutta, jota kukaan koko maailmassa ei ole tehnyt ennen teit&auml;?.   Totisesti ryhdytte himossanne miehiin mieluummin kuin naisiin.  Te olette irstasta v&auml;ke&auml;.&raquo;</p><hr><p class='mb-0'>Koraani (7:80-81)</p>",
				"<p>Sano: »Hän, Jumala on yksi, ainoa Jumala, kaikkivaltias. Hän ei ole (toista) synnyttänyt eikä ole (toisesta) syntynyt. </p><hr><p class='mb-0'>(Koraani 112:1-4)</p>",
				"<p>jotka antavat uhrilahjoja sek&auml; varakkaina ett&auml; k&ouml;yhin&auml; ollessaan, jotka hillitsev&auml;t vihansa ja antavat anteeksi ihmisille; niin, Jumala rakastaa niit&auml;, jotka hyv&auml;&auml; tekev&auml;t. Ja jotka, tehty&auml;&auml;n jotain alhaista tai rikottuaan itse&auml;&auml;n vastaan, muistavat Jumalan ja anovat synti&auml;&auml;n anteeksi (ja kukahan muu kuin Jumala voi antaa synnit anteeksi?) eiv&auml;tk&auml; vastoin parempaa tietoaan paadu siin&auml;, mit&auml; ovat tehneet, </p><hr><p class='mb-0'>(Koraani 3:133-134 )</p>",
				"<p>Sano: »Hän, Jumala on yksi, ainoa Jumala, kaikkivaltias. Hän ei ole (toista) synnyttänyt eikä ole (toisesta) syntynyt. </p><hr><p class='mb-0'>(Koraani 112:1-4)</p> ",
				"<p>Älä ole ylpeä ihmisiä kohtaan, äläkä vaella maassa pöyhkeänä. Totisesti, Jumala ei rakasta omahyväistä kerskuria. Hillitse itsesi ja puhu sävyisästi. Totisesti, rumin ääni on aasin hirnunta.</p><hr><p class='mb-0'>(Koraani 31:18-19)</p>",
				"<p>Sanokaa: &raquo;Me uskomme Jumalaan ja siihen, mik&auml; on ilmoitettu meille ja mik&auml; on ilmoitettu Aabrahamille, Ismaelille, Iisakille ja Jaakobille ja Israelin sukukunnille. </p><hr><p class='mb-0'>(Koraani 2:136)</p>",
				"<p>Muista Lootia, joka sanoi kansalleen: »Harjoitatteko riettautta, vaikka tiedätte sen synniksi? Lähestyttekö himoiten miehiä naisten sijasta? Niin, te olette pimeätä väkeä.» , </p><hr><p class='mb-0'>(Koraani 27:54-55)</p>",
				"<p>Ja Lootille Me annoimme viisautta ja tietoa ja pelastimme hänet kaupungista, jonka asukkaat harjoittivat iljettäviä tekoja. Totisesti, he olivat paha ja hillitön kansa.</p><hr><p class='mb-0'>(Koraani 21:74)</p>",
				"<p>Ja Jumala sanoo: »Alkää ottako itsellenne kahdenlaisia jumalia. Hän Itse on ainoa Jumala, siksi pelätkää vain Minua.» Hänelle kuuluu kaikki, mikä on taivaassa ja maan päällä, ja Häntä on alati toteltava. Palveletteko jotakuta toista kuin Jumalaa?  Kaikki siunaus, minkä saatte, tulee Jumalalta, ja kun teitä kohtaa isku, niin juuri Häntä te avuksenne huudatte. Kun Hän sitten poistaa vaivanne, niin katso, osa teistä asettaa kuitenkin epäjumalia Herransa rinnalle. Niin he kieltävät sen, minkä olemme heille antanut. Nauttikaa siitä! Aikananne saatte kokea. </p><hr><p class='mb-0'>(Koraani 16:51-55)</p>",
				"<p>Totisesti, Jumala käskee jakamaan oikeutta, tekemään hyvää ja harjoittamaan armeliaisuutta sukulaisianne kohtaan; ja Hän kieltää riettaudet, pahuuden ja kapinoimisen; Hän kehoittaa teitä ottamaan vaarin. </p><hr><p class='mb-0'>(Koraani 16:90)</p>",
				"<p>Kirjassa Me ilmoitimme tämän Israelin lapsille näin sanoen: »Totisesti, te teette maan päällä pahaa toistamiseen ja tulette peräti pöyhkeiksi.» Kun täyttyi ensimmäinen kahdesta määräajasta, Me lähetimme teitä vastaan urhoolliset palvelijamme, ja he samosivat voitollisesti halki asutustenne. Ja tämä oli varoitus, jonka oli pakko toteutua. Sen jälkeen Me annoimme teille voiton heistä ja siunasimme teitä rakkaudella ja lapsilla sekä lisäsimme teidän lukumääräänne. Jos teette hyvää, niin teette sen itsellenne, ja jos teette pahaa, niin senkin teette itsellenne. Kun toisen varoituksen aika meni umpeen, niin tapahtui, että palvelijamme peittivät kasvonne murheella, ja he tunkeutuivat moskeijaan kuten ensimmäiselläkin kerralla ja tuhosivat täydellisesti kaiken, minkä löysivät. Voi tapahtua, että Herranne armahtaa teitä, mutta jos käännytte pois, niin Me teemme samoin ja valmistamme helvetin uskottomien vankeuspaikaksi.</p><hr><p class='mb-0'>(Koraani 17:4-8)</p>");
				
	var now = new Date();
	document.getElementById("verse").innerHTML=citat[now.getDate()-1];
	
} 
	

	
	